name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.103' # Versión del SDK.
    - name: Build with dotnet
      run: dotnet build nuget-test/nuget-test/nuget-test.csproj --configuration Release 
    - name: Pack with dotnet
      run: dotnet pack nuget-test/nuget-test/nuget-test.csproj --configuration Release 
    - name: Publish nuget
      run: |
           for f in ./nuget-test/nuget-test/bin/Release/*.nupkg
           do
             curl -vX PUT -u "maxigs7:${{ secrets.GHPackagesToken }}" -F package=@$f https://nuget.pkg.github.com/maxigs7/
           done
      shell: bash
