name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.103' # Versión del SDK.
    - name: Build with dotnet
      run: dotnet build nuget-test/nuget-test/nuget-test.csproj --configuration Release 
    - name: Pack with dotnet
      run: dotnet pack nuget-test/nuget-test/nuget-test.csproj --configuration Release 
    - name: Push Github Package
      run: dotnet nuget push "nuget-test/nuget-test/bin/Release/github-actions-test.1.0.0.nupkg" --source "github"
